name: Release

on:
  push:
    tags:
    - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        architecture: x64

    - name: Install current PDM via pip
      run: python -m pip install -U pdm

    - name: Build artifacts
      run: pdm build

    - name: Test Build
      run: |
        python3 -m venv fresh_env
        . fresh_env/bin/activate
        pip install dist/*.whl

    - name: Get Changelog
      id: get-changelog
      run: |
        awk '/-{3,}/{flag=1;next}/Release/{if (flag==1)exit}flag' ./docs/changelog.md > .changelog.md

    - name: Release
      uses: softprops/action-gh-release@v0.1.14
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: v${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        body_path: .changelog.md
        draft: false
        prerelease: false

    - name: PDM Release Configuration
      run: |
        pdm config repository.pypi.username "__token__"
        pdm config repository.pypi.password ${{ secrets.PYPI_TOKEN }}

    - name: Upload to Pypi
      run: pdm publish
